// @generated
// This file is @generated by prost-build.
/// One decoded Uniswap V3 Swap. Every numeric that can exceed 64 bits is a decimal string:
/// amount0/amount1 are int256 and routinely exceed u64, and truncating them would silently
/// misreport volume.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    #[prost(string, tag="1")]
    pub pool: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub recipient: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount0: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub amount1: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub sqrt_price_x96: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub liquidity: ::prost::alloc::string::String,
    #[prost(int32, tag="8")]
    pub tick: i32,
    #[prost(uint64, tag="9")]
    pub block_number: u64,
    #[prost(int64, tag="10")]
    pub block_timestamp: i64,
    #[prost(string, tag="11")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="12")]
    pub log_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swaps {
    #[prost(message, repeated, tag="1")]
    pub swaps: ::prost::alloc::vec::Vec<Swap>,
}
// @@protoc_insertion_point(module)
